ALTER TYPE status_consulta ADD VALUE IF NOT EXISTS 'ABANDONADO';
ALTER TYPE status_consulta ADD VALUE IF NOT EXISTS 'EXPIRADO';
ALTER TYPE status_consulta ADD VALUE IF NOT EXISTS 'CAPTCHA_INVALIDO';
ALTER TYPE status_consulta ADD VALUE IF NOT EXISTS 'PORTAL_INDISPONIVEL';

ALTER TABLE consultas
  ADD COLUMN IF NOT EXISTS token_consulta TEXT,
  ADD COLUMN IF NOT EXISTS resultado_recebido_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS aba_aberta_em TIMESTAMPTZ;

DROP TABLE IF EXISTS sessoes_automacao;
